### ISSUE TITLE
Little typo on Server-Health

### ISSUE THREAD

**Issue by lucas3v3** [ruanyf/simple-bash-scripts#11]
Where:
`nmap -p- -T4 127.0.0.1`

See:
`nmap -p -T4 127.0.0.1`

https://github.com/ruanyf/simple-bash-scripts/blob/6b289dea9586e0558e3808c91a4cf7c13d699c8a/scripts/Server-Health.sh#L26

**Comment by ruanyf** [comment]
Thanks. fixed it.
