### ISSUE TITLE
How to run text menu script automatically on every reboot

### ISSUE THREAD

**Issue by tahirahmad1985** [ruanyf/simple-bash-scripts#3]
This script has an output, which shows a text menu with few options 1,2,3..

What I want to do!!!

I want to run this script automatically and automatically selects option 2 on every start/reboot of Linux system.

I need some one to help me

#!/bin/bash
# Bash Menu Script Example

PS3='Please enter your choice: '
options=("Option 1" "Option 2" "Option 3" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Option 1")
            echo "you chose choice 1"
            ;;
        "Option 2")
            echo "you chose choice 2"
            ;;
        "Option 3")
            echo "you chose choice 3"
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done

Output is as follows:
 "Choose your option:"

1) Option 1  
2) Option 2  
3) Option 3  
4) Quit  

I also know that to run it automatically on every reboot, I need to give the complete path in /etc/rc.local file

But how to run this automatically on every reboot with automatic selection of option 2

**Comment by ruanyf** [comment]
You should put your script codes in `~/.bashrc`.
